import { PROFESSIONAL_IMAGES, USER_IMAGE } from '@/constants/images';
import { Booking, Message, Professional, User } from '@/types';

export const MOCK_USER: User = {
  id: 'user-1',
  name: 'Marco Rossi',
  email: 'marco.rossi@email.com',
  imageUrl: USER_IMAGE,
  avatarColor: '#3B82F6',
  memberSince: 'Gennaio 2024',
  stats: { bookings: 12, completed: 8, rating: 4.9 },
};

export const MOCK_PROFESSIONALS: Professional[] = [
  {
    id: '1',
    name: 'Laura Bianchi',
    categorySlug: 'pulizie',
    category: 'Pulizie',
    imageUrl: PROFESSIONAL_IMAGES['1'].avatar,
    heroImageUrl: PROFESSIONAL_IMAGES['1'].hero,
    avatarColor: '#8B5CF6',
    rating: 4.9,
    reviewCount: 127,
    jobsCompleted: 340,
    pricePerHour: 25,
    distanceKm: 1.2,
    availableToday: true,
    verified: true,
    badges: { document: true, phone: true, professional: true },
    bio: 'Specializzata in pulizie domestiche e post-ristrutturazione. Uso prodotti eco-friendly e garantisco risultati impeccabili.',
    whyChoose: [
      'Prodotti eco-friendly certificati',
      'Puntualità garantita al 100%',
      'Assicurazione RC professionale',
      'Oltre 340 lavori completati',
    ],
    packages: [
      { id: 'p1', tier: 'base', title: 'Base', description: 'Pulizia standard appartamento fino a 60mq', price: 45, duration: '2 ore' },
      { id: 'p2', tier: 'standard', title: 'Standard', description: 'Pulizia profonda con dettagli e vetri', price: 85, duration: '4 ore' },
      { id: 'p3', tier: 'premium', title: 'Premium', description: 'Post-ristrutturazione completa + sanificazione', price: 120, duration: '5 ore' },
    ],
  },
  {
    id: '2',
    name: 'Luca Bianchi',
    categorySlug: 'idraulici',
    category: 'Idraulico',
    imageUrl: PROFESSIONAL_IMAGES['2'].avatar,
    heroImageUrl: PROFESSIONAL_IMAGES['2'].hero,
    avatarColor: '#0EA5E9',
    rating: 4.8,
    reviewCount: 95,
    jobsCompleted: 180,
    pricePerHour: 30,
    distanceKm: 1.2,
    availableToday: true,
    verified: true,
    badges: { document: true, phone: true, professional: true },
    bio: 'Idraulico con 15 anni di esperienza. Interventi rapidi per perdite, installazioni e manutenzione impianti.',
    whyChoose: [
      'Interventi rapidi e puntuali',
      'Prezzi trasparenti senza sorprese',
      'Materiali di qualità certificati',
      'Assistenza post-intervento inclusa',
    ],
    packages: [
      { id: 'p1', tier: 'base', title: 'Intervento base', description: 'Diagnosi e riparazione perdite semplici', price: 40, duration: '1-2 ore' },
      { id: 'p2', tier: 'standard', title: 'Intervento standard', description: 'Installazione rubinetteria e collaudo', price: 90, duration: '2-3 ore' },
      { id: 'p3', tier: 'premium', title: 'Intervento premium', description: 'Manutenzione completa impianto e caldaia', price: 150, duration: '3-4 ore' },
    ],
  },
  {
    id: '3',
    name: 'Anna Ferrari',
    categorySlug: 'elettricisti',
    category: 'Elettricista',
    imageUrl: PROFESSIONAL_IMAGES['3'].avatar,
    heroImageUrl: PROFESSIONAL_IMAGES['3'].hero,
    avatarColor: '#F59E0B',
    rating: 5.0,
    reviewCount: 64,
    jobsCompleted: 180,
    pricePerHour: 45,
    distanceKm: 2.1,
    availableToday: true,
    verified: true,
    badges: { document: true, phone: true, professional: true },
    bio: 'Elettricista certificata. Impianti civili, illuminazione LED e domotica. Lavoro conforme alle normative.',
    whyChoose: [
      'Certificazione DM 37/08',
      'Domotica e smart home',
      'Garanzia 24 mesi sui lavori',
      'Valutazione 5.0 stelle',
    ],
    packages: [
      { id: 'p1', tier: 'base', title: 'Base', description: 'Installazione punto luce singolo', price: 55, duration: '1 ora' },
      { id: 'p2', tier: 'standard', title: 'Standard', description: 'Verifica e aggiornamento quadro elettrico', price: 180, duration: '4 ore' },
      { id: 'p3', tier: 'premium', title: 'Premium', description: 'Configurazione domotica completa', price: 250, duration: '6 ore' },
    ],
  },
  {
    id: '4',
    name: 'Paolo Russo',
    categorySlug: 'giardinieri',
    category: 'Giardiniere',
    imageUrl: PROFESSIONAL_IMAGES['4'].avatar,
    heroImageUrl: PROFESSIONAL_IMAGES['4'].hero,
    avatarColor: '#10B981',
    rating: 4.7,
    reviewCount: 52,
    jobsCompleted: 145,
    pricePerHour: 30,
    distanceKm: 3.4,
    availableToday: false,
    verified: true,
    badges: { document: true, phone: true, professional: false },
    bio: 'Giardiniere appassionato. Potature, manutenzione prati e progettazione spazi verdi.',
    whyChoose: [
      'Progettazione paesaggistica',
      'Potatura certificata alberi',
      'Manutenzione stagionale',
      'Attrezzatura professionale',
    ],
    packages: [
      { id: 'p1', tier: 'base', title: 'Base', description: 'Manutenzione giardino fino a 100mq', price: 70, duration: '3 ore' },
      { id: 'p2', tier: 'standard', title: 'Standard', description: 'Potatura professionale alberi', price: 100, duration: '4 ore' },
      { id: 'p3', tier: 'premium', title: 'Premium', description: 'Consulenza e impianto verde completo', price: 200, duration: '8 ore' },
    ],
  },
  {
    id: '5',
    name: 'Luca Conti',
    categorySlug: 'tuttofare',
    category: 'Tuttofare',
    imageUrl: PROFESSIONAL_IMAGES['5'].avatar,
    heroImageUrl: PROFESSIONAL_IMAGES['5'].hero,
    avatarColor: '#6366F1',
    rating: 4.6,
    reviewCount: 98,
    jobsCompleted: 290,
    pricePerHour: 35,
    distanceKm: 1.8,
    availableToday: true,
    verified: true,
    badges: { document: true, phone: true, professional: true },
    bio: 'Tuttofare versatile: montaggi mobili, piccole riparazioni, pittura e lavori domestici.',
    whyChoose: [
      'Disponibilità flessibile',
      'Montaggio mobili IKEA e simili',
      'Attrezzi professionali inclusi',
      '290 lavori completati',
    ],
    packages: [
      { id: 'p1', tier: 'base', title: 'Base', description: 'Montaggio mobili singolo', price: 50, duration: '2 ore' },
      { id: 'p2', tier: 'standard', title: 'Standard', description: 'Riparazioni domestiche multiple', price: 65, duration: '2 ore' },
      { id: 'p3', tier: 'premium', title: 'Premium', description: 'Pittura stanza fino a 15mq', price: 150, duration: '6 ore' },
    ],
  },
  {
    id: '6',
    name: 'Sofia Marino',
    categorySlug: 'pulizie',
    category: 'Pulizie',
    imageUrl: PROFESSIONAL_IMAGES['6'].avatar,
    heroImageUrl: PROFESSIONAL_IMAGES['6'].hero,
    avatarColor: '#EC4899',
    rating: 4.8,
    reviewCount: 73,
    jobsCompleted: 195,
    pricePerHour: 22,
    distanceKm: 0.5,
    availableToday: true,
    verified: true,
    badges: { document: true, phone: true, professional: true },
    bio: 'Pulizie professionali per uffici e abitazioni. Puntualità e attenzione ai dettagli.',
    whyChoose: [
      'Specialista uffici e abitazioni',
      'Prodotti ipoallergenici',
      'Team di 2 persone su richiesta',
      'Abbonamenti settimanali',
    ],
    packages: [
      { id: 'p1', tier: 'base', title: 'Base', description: 'Pulizia ufficio fino a 80mq', price: 60, duration: '3 ore' },
      { id: 'p2', tier: 'standard', title: 'Standard', description: 'Pulizia settimanale 4 sessioni', price: 160, duration: '8 ore' },
      { id: 'p3', tier: 'premium', title: 'Premium', description: 'Sanificazione antibatterica completa', price: 95, duration: '3 ore' },
    ],
  },
  {
    id: '7',
    name: 'Giulia Costa',
    categorySlug: 'pulizie',
    category: 'Pulizie',
    imageUrl: PROFESSIONAL_IMAGES['7'].avatar,
    heroImageUrl: PROFESSIONAL_IMAGES['7'].hero,
    avatarColor: '#14B8A6',
    rating: 4.7,
    reviewCount: 89,
    jobsCompleted: 210,
    pricePerHour: 23,
    distanceKm: 2.3,
    availableToday: true,
    verified: true,
    badges: { document: true, phone: true, professional: true },
    bio: 'Esperta in pulizie profonde e sanificazione.',
    whyChoose: ['Prodotti ecologici', 'Flessibilità oraria'],
    packages: [
      { id: 'p1', tier: 'base', title: 'Base', description: 'Pulizia standard', price: 45, duration: '2 ore' },
      { id: 'p2', tier: 'standard', title: 'Standard', description: 'Pulizia profonda', price: 75, duration: '3 ore' },
      { id: 'p3', tier: 'premium', title: 'Premium', description: 'Sanificazione completa', price: 110, duration: '4 ore' },
    ],
  },
  {
    id: '8',
    name: 'Marco De Luca',
    categorySlug: 'idraulici',
    category: 'Idraulico',
    imageUrl: PROFESSIONAL_IMAGES['8'].avatar,
    heroImageUrl: PROFESSIONAL_IMAGES['8'].hero,
    avatarColor: '#0284C7',
    rating: 4.9,
    reviewCount: 112,
    jobsCompleted: 220,
    pricePerHour: 32,
    distanceKm: 0.9,
    availableToday: true,
    verified: true,
    badges: { document: true, phone: true, professional: true },
    bio: 'Specialista in perdite e installazioni bagno.',
    whyChoose: ['Interventi rapidi', 'Garanzia lavori'],
    packages: [
      { id: 'p1', tier: 'base', title: 'Base', description: 'Riparazione perdite', price: 45, duration: '1-2 ore' },
      { id: 'p2', tier: 'standard', title: 'Standard', description: 'Installazione sanitari', price: 95, duration: '3 ore' },
      { id: 'p3', tier: 'premium', title: 'Premium', description: 'Rifacimento bagno', price: 180, duration: '6 ore' },
    ],
  },
  {
    id: '9',
    name: 'Andrea Neri',
    categorySlug: 'idraulici',
    category: 'Idraulico',
    imageUrl: PROFESSIONAL_IMAGES['9'].avatar,
    heroImageUrl: PROFESSIONAL_IMAGES['9'].hero,
    avatarColor: '#0369A1',
    rating: 4.6,
    reviewCount: 67,
    jobsCompleted: 150,
    pricePerHour: 28,
    distanceKm: 2.8,
    availableToday: false,
    verified: true,
    badges: { document: true, phone: true, professional: true },
    bio: 'Manutenzione caldaie e impianti idraulici.',
    whyChoose: ['Certificato', 'Preventivo gratuito'],
    packages: [
      { id: 'p1', tier: 'base', title: 'Base', description: 'Controllo impianto', price: 50, duration: '1 ora' },
      { id: 'p2', tier: 'standard', title: 'Standard', description: 'Manutenzione caldaia', price: 120, duration: '2 ore' },
      { id: 'p3', tier: 'premium', title: 'Premium', description: 'Sostituzione caldaia', price: 200, duration: '4 ore' },
    ],
  },
  {
    id: '10',
    name: 'Roberto Galli',
    categorySlug: 'elettricisti',
    category: 'Elettricista',
    imageUrl: PROFESSIONAL_IMAGES['10'].avatar,
    heroImageUrl: PROFESSIONAL_IMAGES['10'].hero,
    avatarColor: '#D97706',
    rating: 4.8,
    reviewCount: 88,
    jobsCompleted: 200,
    pricePerHour: 40,
    distanceKm: 1.5,
    availableToday: true,
    verified: true,
    badges: { document: true, phone: true, professional: true },
    bio: 'Impianti civili e industriali, illuminazione LED.',
    whyChoose: ['Certificato', 'Domotica'],
    packages: [
      { id: 'p1', tier: 'base', title: 'Base', description: 'Punto luce', price: 50, duration: '1 ora' },
      { id: 'p2', tier: 'standard', title: 'Standard', description: 'Quadro elettrico', price: 170, duration: '4 ore' },
      { id: 'p3', tier: 'premium', title: 'Premium', description: 'Impianto completo', price: 280, duration: '8 ore' },
    ],
  },
  {
    id: '11',
    name: 'Elena Vitale',
    categorySlug: 'elettricisti',
    category: 'Elettricista',
    imageUrl: PROFESSIONAL_IMAGES['11'].avatar,
    heroImageUrl: PROFESSIONAL_IMAGES['11'].hero,
    avatarColor: '#F59E0B',
    rating: 4.7,
    reviewCount: 54,
    jobsCompleted: 130,
    pricePerHour: 42,
    distanceKm: 3.1,
    availableToday: true,
    verified: true,
    badges: { document: true, phone: true, professional: true },
    bio: 'Smart home e automazione domestica.',
    whyChoose: ['Esperta domotica', 'Puntualità'],
    packages: [
      { id: 'p1', tier: 'base', title: 'Base', description: 'Configurazione smart', price: 60, duration: '2 ore' },
      { id: 'p2', tier: 'standard', title: 'Standard', description: 'Illuminazione LED', price: 140, duration: '3 ore' },
      { id: 'p3', tier: 'premium', title: 'Premium', description: 'Sistema domotico', price: 320, duration: '8 ore' },
    ],
  },
  {
    id: '12',
    name: 'Francesco Verde',
    categorySlug: 'giardinieri',
    category: 'Giardiniere',
    imageUrl: PROFESSIONAL_IMAGES['12'].avatar,
    heroImageUrl: PROFESSIONAL_IMAGES['12'].hero,
    avatarColor: '#059669',
    rating: 4.8,
    reviewCount: 76,
    jobsCompleted: 190,
    pricePerHour: 28,
    distanceKm: 2.0,
    availableToday: true,
    verified: true,
    badges: { document: true, phone: true, professional: true },
    bio: 'Potature e manutenzione giardini residenziali.',
    whyChoose: ['Attrezzatura propria', 'Sopralluogo gratuito'],
    packages: [
      { id: 'p1', tier: 'base', title: 'Base', description: 'Taglio erba', price: 55, duration: '2 ore' },
      { id: 'p2', tier: 'standard', title: 'Standard', description: 'Potatura siepi', price: 85, duration: '3 ore' },
      { id: 'p3', tier: 'premium', title: 'Premium', description: 'Rifacimento giardino', price: 220, duration: '8 ore' },
    ],
  },
  {
    id: '13',
    name: 'Chiara Bosco',
    categorySlug: 'giardinieri',
    category: 'Giardiniere',
    imageUrl: PROFESSIONAL_IMAGES['13'].avatar,
    heroImageUrl: PROFESSIONAL_IMAGES['13'].hero,
    avatarColor: '#22C55E',
    rating: 4.9,
    reviewCount: 61,
    jobsCompleted: 165,
    pricePerHour: 32,
    distanceKm: 4.2,
    availableToday: false,
    verified: true,
    badges: { document: true, phone: true, professional: true },
    bio: 'Progettazione e cura del verde ornamentale.',
    whyChoose: ['Design paesaggistico', 'Piante certificate'],
    packages: [
      { id: 'p1', tier: 'base', title: 'Base', description: 'Manutenzione mensile', price: 65, duration: '3 ore' },
      { id: 'p2', tier: 'standard', title: 'Standard', description: 'Potatura alberi', price: 110, duration: '4 ore' },
      { id: 'p3', tier: 'premium', title: 'Premium', description: 'Nuovo impianto verde', price: 250, duration: '10 ore' },
    ],
  },
  {
    id: '14',
    name: 'Davide Moretti',
    categorySlug: 'tuttofare',
    category: 'Tuttofare',
    imageUrl: PROFESSIONAL_IMAGES['14'].avatar,
    heroImageUrl: PROFESSIONAL_IMAGES['14'].hero,
    avatarColor: '#64748B',
    rating: 4.7,
    reviewCount: 102,
    jobsCompleted: 260,
    pricePerHour: 32,
    distanceKm: 1.1,
    availableToday: true,
    verified: true,
    badges: { document: true, phone: true, professional: true },
    bio: 'Montaggi, riparazioni e piccoli lavori domestici.',
    whyChoose: ['Multicompetente', 'Disponibile weekend'],
    packages: [
      { id: 'p1', tier: 'base', title: 'Base', description: 'Montaggio mobili', price: 45, duration: '2 ore' },
      { id: 'p2', tier: 'standard', title: 'Standard', description: 'Riparazioni varie', price: 60, duration: '2 ore' },
      { id: 'p3', tier: 'premium', title: 'Premium', description: 'Pittura interna', price: 140, duration: '6 ore' },
    ],
  },
  {
    id: '15',
    name: 'Simone Riva',
    categorySlug: 'tuttofare',
    category: 'Tuttofare',
    imageUrl: PROFESSIONAL_IMAGES['15'].avatar,
    heroImageUrl: PROFESSIONAL_IMAGES['15'].hero,
    avatarColor: '#475569',
    rating: 4.5,
    reviewCount: 78,
    jobsCompleted: 175,
    pricePerHour: 30,
    distanceKm: 2.6,
    availableToday: true,
    verified: false,
    badges: { document: true, phone: true, professional: false },
    bio: 'Tuttofare per casa e ufficio, montaggi e fissaggi.',
    whyChoose: ['Prezzi chiari', 'Lavoro pulito'],
    packages: [
      { id: 'p1', tier: 'base', title: 'Base', description: 'Fissaggi a muro', price: 35, duration: '1 ora' },
      { id: 'p2', tier: 'standard', title: 'Standard', description: 'Montaggio armadi', price: 70, duration: '3 ore' },
      { id: 'p3', tier: 'premium', title: 'Premium', description: 'Lavori multipli', price: 120, duration: '5 ore' },
    ],
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'b1',
    professionalId: '1',
    professionalName: 'Laura Bianchi',
    professionalImageUrl: PROFESSIONAL_IMAGES['1'].avatar,
    category: 'Pulizie',
    serviceTitle: 'Pulizia casa',
    date: '12 Giu 2024',
    time: '10:00',
    status: 'confirmed',
    price: 85,
    address: 'Via Roma 12, Milano',
    note: 'Piano secondo, citofono Bianchi. Attenzione al parquet in soggiorno.',
  },
  {
    id: 'b2',
    professionalId: '2',
    professionalName: 'Luca Bianchi',
    professionalImageUrl: PROFESSIONAL_IMAGES['2'].avatar,
    category: 'Idraulico',
    serviceTitle: 'Riparazione perdita',
    date: '8 Giu 2024',
    time: '14:30',
    status: 'incoming',
    price: 60,
    address: 'Corso Garibaldi 45, Milano',
    note: 'Perdita sotto il lavello della cucina.',
  },
  {
    id: 'b3',
    professionalId: '5',
    professionalName: 'Luca Conti',
    professionalImageUrl: PROFESSIONAL_IMAGES['5'].avatar,
    category: 'Tuttofare',
    serviceTitle: 'Montaggio mobili',
    date: '28 Mag 2024',
    time: '09:00',
    status: 'completed',
    price: 50,
    address: 'Viale Monza 88, Milano',
  },
  {
    id: 'b4',
    professionalId: '3',
    professionalName: 'Anna Ferrari',
    professionalImageUrl: PROFESSIONAL_IMAGES['3'].avatar,
    category: 'Elettricista',
    serviceTitle: 'Punto luce',
    date: '15 Mag 2024',
    time: '11:00',
    status: 'completed',
    price: 55,
    address: 'Piazza Duomo 3, Milano',
  },
];

export function getBookingById(id: string): Booking | undefined {
  return MOCK_BOOKINGS.find((booking) => booking.id === id);
}

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'm1',
    professionalId: '1',
    professionalName: 'Laura Bianchi',
    imageUrl: PROFESSIONAL_IMAGES['1'].avatar,
    avatarColor: '#8B5CF6',
    lastMessage: 'Perfetto, ci vediamo martedì alle 10!',
    timestamp: '10:32',
    unread: 2,
  },
  {
    id: 'm2',
    professionalId: '2',
    professionalName: 'Luca Bianchi',
    imageUrl: PROFESSIONAL_IMAGES['2'].avatar,
    avatarColor: '#0EA5E9',
    lastMessage: 'Ho risolto la perdita, tutto a posto.',
    timestamp: 'Ieri',
    unread: 0,
  },
  {
    id: 'm3',
    professionalId: '5',
    professionalName: 'Luca Conti',
    imageUrl: PROFESSIONAL_IMAGES['5'].avatar,
    avatarColor: '#6366F1',
    lastMessage: 'Porto gli attrezzi necessari.',
    timestamp: 'Lun',
    unread: 0,
  },
];

export function getProfessionalById(id: string): Professional | undefined {
  return MOCK_PROFESSIONALS.find((p) => p.id === id);
}

export function getProfessionalsByCategory(slug: string): Professional[] {
  return MOCK_PROFESSIONALS.filter((p) => p.categorySlug === slug);
}

export function getTopProfessionalsByCategory(slug: string, limit = 4): Professional[] {
  return getProfessionalsByCategory(slug)
    .sort((a, b) => b.rating - a.rating || b.reviewCount - a.reviewCount)
    .slice(0, limit);
}

export function getSoonAvailableByCategory(slug: string, limit = 6): Professional[] {
  const inCategory = getProfessionalsByCategory(slug);
  const available = inCategory
    .filter((p) => p.availableToday)
    .sort((a, b) => a.distanceKm - b.distanceKm);

  if (available.length >= limit) {
    return available.slice(0, limit);
  }

  const rest = inCategory
    .filter((p) => !p.availableToday)
    .sort((a, b) => b.rating - a.rating);

  return [...available, ...rest].slice(0, limit);
}

export function getAvailableToday(): Professional[] {
  return MOCK_PROFESSIONALS.filter((p) => p.availableToday);
}

export function getRecommendedProfessionals(): Professional[] {
  return [...MOCK_PROFESSIONALS]
    .sort((a, b) => b.rating - a.rating)
    .slice(0, 4);
}
