-- Seed zone professionals (Barletta area) — generated by seed-zone-professionals.mjs
-- Idempotente: UUID stabili b2000001-…, legacy_id 900001+ (no conflitto con seed esistenti).
-- Non elimina professionisti preesistenti.
-- Almeno 1 verified pro per categoria con Barletta in service_areas.

INSERT INTO professionals (
  id, legacy_id, category_id, category_slug, name, category_label,
  image_url, hero_image_url, avatar_color, bio, why_choose,
  rating, review_count, jobs_completed, price_per_hour, distance_km,
  available_today, verified, badge_document, badge_phone, badge_professional,
  base_city, service_areas, urgent_badge, is_new_featured, account_status
) VALUES (
  'b2000001-0001-4000-8000-000000000001', '900001', 'c1000001-0001-4000-8000-000000000003', 'elettricisti', 'Anna Ferrari', 'Elettricista',
  'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&h=200&fit=crop&crop=face', 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&h=600&fit=crop', '#F59E0B',
  'Professionista verificato su Fidati, disponibile per interventi rapidi e lavori programmati.', '["Recensioni verificate","Prezzi trasparenti","Assicurazione RC professionale"]'::jsonb,
  5, 64, 154, 45, 2.1,
  true, true, true, true, true,
  'Trani', ARRAY['Trani', 'Barletta', 'Margherita di Savoia']::TEXT[],
  'Oggi', true, 'verified'
) ON CONFLICT (id) DO UPDATE SET
  legacy_id = COALESCE(professionals.legacy_id, EXCLUDED.legacy_id),
  category_id = EXCLUDED.category_id,
  category_slug = EXCLUDED.category_slug,
  name = EXCLUDED.name,
  category_label = EXCLUDED.category_label,
  image_url = EXCLUDED.image_url,
  hero_image_url = EXCLUDED.hero_image_url,
  avatar_color = EXCLUDED.avatar_color,
  bio = EXCLUDED.bio,
  why_choose = EXCLUDED.why_choose,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  jobs_completed = EXCLUDED.jobs_completed,
  price_per_hour = EXCLUDED.price_per_hour,
  distance_km = EXCLUDED.distance_km,
  available_today = EXCLUDED.available_today,
  verified = EXCLUDED.verified,
  badge_document = EXCLUDED.badge_document,
  badge_phone = EXCLUDED.badge_phone,
  badge_professional = EXCLUDED.badge_professional,
  base_city = EXCLUDED.base_city,
  service_areas = EXCLUDED.service_areas,
  urgent_badge = EXCLUDED.urgent_badge,
  is_new_featured = EXCLUDED.is_new_featured,
  account_status = EXCLUDED.account_status;

INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000001', 'Trani', 1) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000001', 'Barletta', 2) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000001', 'Margherita di Savoia', 3) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;

INSERT INTO professionals (
  id, legacy_id, category_id, category_slug, name, category_label,
  image_url, hero_image_url, avatar_color, bio, why_choose,
  rating, review_count, jobs_completed, price_per_hour, distance_km,
  available_today, verified, badge_document, badge_phone, badge_professional,
  base_city, service_areas, urgent_badge, is_new_featured, account_status
) VALUES (
  'b2000001-0001-4000-8000-000000000002', '900002', 'c1000001-0001-4000-8000-000000000003', 'elettricisti', 'Marco Vitale', 'Elettricista',
  'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face', 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=800&h=600&fit=crop', '#D97706',
  'Professionista verificato su Fidati, disponibile per interventi rapidi e lavori programmati.', '["Recensioni verificate","Prezzi trasparenti","Assicurazione RC professionale"]'::jsonb,
  4.9, 88, 211, 42, 1.4,
  true, true, true, true, true,
  'Barletta', ARRAY['Barletta', 'Andria', 'Bisceglie']::TEXT[],
  NULL, false, 'verified'
) ON CONFLICT (id) DO UPDATE SET
  legacy_id = COALESCE(professionals.legacy_id, EXCLUDED.legacy_id),
  category_id = EXCLUDED.category_id,
  category_slug = EXCLUDED.category_slug,
  name = EXCLUDED.name,
  category_label = EXCLUDED.category_label,
  image_url = EXCLUDED.image_url,
  hero_image_url = EXCLUDED.hero_image_url,
  avatar_color = EXCLUDED.avatar_color,
  bio = EXCLUDED.bio,
  why_choose = EXCLUDED.why_choose,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  jobs_completed = EXCLUDED.jobs_completed,
  price_per_hour = EXCLUDED.price_per_hour,
  distance_km = EXCLUDED.distance_km,
  available_today = EXCLUDED.available_today,
  verified = EXCLUDED.verified,
  badge_document = EXCLUDED.badge_document,
  badge_phone = EXCLUDED.badge_phone,
  badge_professional = EXCLUDED.badge_professional,
  base_city = EXCLUDED.base_city,
  service_areas = EXCLUDED.service_areas,
  urgent_badge = EXCLUDED.urgent_badge,
  is_new_featured = EXCLUDED.is_new_featured,
  account_status = EXCLUDED.account_status;

INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000002', 'Barletta', 1) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000002', 'Andria', 2) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000002', 'Bisceglie', 3) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;

INSERT INTO professionals (
  id, legacy_id, category_id, category_slug, name, category_label,
  image_url, hero_image_url, avatar_color, bio, why_choose,
  rating, review_count, jobs_completed, price_per_hour, distance_km,
  available_today, verified, badge_document, badge_phone, badge_professional,
  base_city, service_areas, urgent_badge, is_new_featured, account_status
) VALUES (
  'b2000001-0001-4000-8000-000000000003', '900003', 'c1000001-0001-4000-8000-000000000003', 'elettricisti', 'Paolo Greco', 'Elettricista',
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face', 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=600&fit=crop', '#B45309',
  'Professionista verificato su Fidati, disponibile per interventi rapidi e lavori programmati.', '["Recensioni verificate","Prezzi trasparenti","Assicurazione RC professionale"]'::jsonb,
  4.8, 71, 170, 40, 3.2,
  false, true, true, true, true,
  'Andria', ARRAY['Andria', 'Barletta', 'Trani']::TEXT[],
  NULL, false, 'verified'
) ON CONFLICT (id) DO UPDATE SET
  legacy_id = COALESCE(professionals.legacy_id, EXCLUDED.legacy_id),
  category_id = EXCLUDED.category_id,
  category_slug = EXCLUDED.category_slug,
  name = EXCLUDED.name,
  category_label = EXCLUDED.category_label,
  image_url = EXCLUDED.image_url,
  hero_image_url = EXCLUDED.hero_image_url,
  avatar_color = EXCLUDED.avatar_color,
  bio = EXCLUDED.bio,
  why_choose = EXCLUDED.why_choose,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  jobs_completed = EXCLUDED.jobs_completed,
  price_per_hour = EXCLUDED.price_per_hour,
  distance_km = EXCLUDED.distance_km,
  available_today = EXCLUDED.available_today,
  verified = EXCLUDED.verified,
  badge_document = EXCLUDED.badge_document,
  badge_phone = EXCLUDED.badge_phone,
  badge_professional = EXCLUDED.badge_professional,
  base_city = EXCLUDED.base_city,
  service_areas = EXCLUDED.service_areas,
  urgent_badge = EXCLUDED.urgent_badge,
  is_new_featured = EXCLUDED.is_new_featured,
  account_status = EXCLUDED.account_status;

INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000003', 'Andria', 1) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000003', 'Barletta', 2) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000003', 'Trani', 3) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;

INSERT INTO professionals (
  id, legacy_id, category_id, category_slug, name, category_label,
  image_url, hero_image_url, avatar_color, bio, why_choose,
  rating, review_count, jobs_completed, price_per_hour, distance_km,
  available_today, verified, badge_document, badge_phone, badge_professional,
  base_city, service_areas, urgent_badge, is_new_featured, account_status
) VALUES (
  'b2000001-0001-4000-8000-000000000004', '900004', 'c1000001-0001-4000-8000-000000000002', 'idraulici', 'Luca Bianchi', 'Idraulico',
  'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&h=200&fit=crop&crop=face', 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=800&h=600&fit=crop', '#0EA5E9',
  'Professionista verificato su Fidati, disponibile per interventi rapidi e lavori programmati.', '["Recensioni verificate","Prezzi trasparenti","Assicurazione RC professionale"]'::jsonb,
  4.8, 95, 228, 30, 1.2,
  true, true, true, true, true,
  'Barletta', ARRAY['Barletta', 'Andria', 'Bisceglie']::TEXT[],
  'Entro 1 ora', true, 'verified'
) ON CONFLICT (id) DO UPDATE SET
  legacy_id = COALESCE(professionals.legacy_id, EXCLUDED.legacy_id),
  category_id = EXCLUDED.category_id,
  category_slug = EXCLUDED.category_slug,
  name = EXCLUDED.name,
  category_label = EXCLUDED.category_label,
  image_url = EXCLUDED.image_url,
  hero_image_url = EXCLUDED.hero_image_url,
  avatar_color = EXCLUDED.avatar_color,
  bio = EXCLUDED.bio,
  why_choose = EXCLUDED.why_choose,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  jobs_completed = EXCLUDED.jobs_completed,
  price_per_hour = EXCLUDED.price_per_hour,
  distance_km = EXCLUDED.distance_km,
  available_today = EXCLUDED.available_today,
  verified = EXCLUDED.verified,
  badge_document = EXCLUDED.badge_document,
  badge_phone = EXCLUDED.badge_phone,
  badge_professional = EXCLUDED.badge_professional,
  base_city = EXCLUDED.base_city,
  service_areas = EXCLUDED.service_areas,
  urgent_badge = EXCLUDED.urgent_badge,
  is_new_featured = EXCLUDED.is_new_featured,
  account_status = EXCLUDED.account_status;

INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000004', 'Barletta', 1) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000004', 'Andria', 2) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000004', 'Bisceglie', 3) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;

INSERT INTO professionals (
  id, legacy_id, category_id, category_slug, name, category_label,
  image_url, hero_image_url, avatar_color, bio, why_choose,
  rating, review_count, jobs_completed, price_per_hour, distance_km,
  available_today, verified, badge_document, badge_phone, badge_professional,
  base_city, service_areas, urgent_badge, is_new_featured, account_status
) VALUES (
  'b2000001-0001-4000-8000-000000000005', '900005', 'c1000001-0001-4000-8000-000000000002', 'idraulici', 'Francesco De Luca', 'Idraulico',
  'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&h=200&fit=crop&crop=face', 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=800&h=600&fit=crop', '#0284C7',
  'Professionista verificato su Fidati, disponibile per interventi rapidi e lavori programmati.', '["Recensioni verificate","Prezzi trasparenti","Assicurazione RC professionale"]'::jsonb,
  4.7, 82, 197, 32, 2,
  true, true, true, true, true,
  'Andria', ARRAY['Andria', 'Barletta', 'Trani']::TEXT[],
  NULL, false, 'verified'
) ON CONFLICT (id) DO UPDATE SET
  legacy_id = COALESCE(professionals.legacy_id, EXCLUDED.legacy_id),
  category_id = EXCLUDED.category_id,
  category_slug = EXCLUDED.category_slug,
  name = EXCLUDED.name,
  category_label = EXCLUDED.category_label,
  image_url = EXCLUDED.image_url,
  hero_image_url = EXCLUDED.hero_image_url,
  avatar_color = EXCLUDED.avatar_color,
  bio = EXCLUDED.bio,
  why_choose = EXCLUDED.why_choose,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  jobs_completed = EXCLUDED.jobs_completed,
  price_per_hour = EXCLUDED.price_per_hour,
  distance_km = EXCLUDED.distance_km,
  available_today = EXCLUDED.available_today,
  verified = EXCLUDED.verified,
  badge_document = EXCLUDED.badge_document,
  badge_phone = EXCLUDED.badge_phone,
  badge_professional = EXCLUDED.badge_professional,
  base_city = EXCLUDED.base_city,
  service_areas = EXCLUDED.service_areas,
  urgent_badge = EXCLUDED.urgent_badge,
  is_new_featured = EXCLUDED.is_new_featured,
  account_status = EXCLUDED.account_status;

INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000005', 'Andria', 1) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000005', 'Barletta', 2) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000005', 'Trani', 3) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;

INSERT INTO professionals (
  id, legacy_id, category_id, category_slug, name, category_label,
  image_url, hero_image_url, avatar_color, bio, why_choose,
  rating, review_count, jobs_completed, price_per_hour, distance_km,
  available_today, verified, badge_document, badge_phone, badge_professional,
  base_city, service_areas, urgent_badge, is_new_featured, account_status
) VALUES (
  'b2000001-0001-4000-8000-000000000006', '900006', 'c1000001-0001-4000-8000-000000000001', 'pulizie', 'Laura Bianchi', 'Pulizie',
  'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop&crop=face', 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&h=600&fit=crop', '#8B5CF6',
  'Professionista verificato su Fidati, disponibile per interventi rapidi e lavori programmati.', '["Recensioni verificate","Prezzi trasparenti","Assicurazione RC professionale"]'::jsonb,
  4.92, 128, 307, 25, 1.2,
  true, true, true, true, true,
  'Barletta', ARRAY['Barletta', 'Andria', 'Trani']::TEXT[],
  'Oggi', true, 'verified'
) ON CONFLICT (id) DO UPDATE SET
  legacy_id = COALESCE(professionals.legacy_id, EXCLUDED.legacy_id),
  category_id = EXCLUDED.category_id,
  category_slug = EXCLUDED.category_slug,
  name = EXCLUDED.name,
  category_label = EXCLUDED.category_label,
  image_url = EXCLUDED.image_url,
  hero_image_url = EXCLUDED.hero_image_url,
  avatar_color = EXCLUDED.avatar_color,
  bio = EXCLUDED.bio,
  why_choose = EXCLUDED.why_choose,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  jobs_completed = EXCLUDED.jobs_completed,
  price_per_hour = EXCLUDED.price_per_hour,
  distance_km = EXCLUDED.distance_km,
  available_today = EXCLUDED.available_today,
  verified = EXCLUDED.verified,
  badge_document = EXCLUDED.badge_document,
  badge_phone = EXCLUDED.badge_phone,
  badge_professional = EXCLUDED.badge_professional,
  base_city = EXCLUDED.base_city,
  service_areas = EXCLUDED.service_areas,
  urgent_badge = EXCLUDED.urgent_badge,
  is_new_featured = EXCLUDED.is_new_featured,
  account_status = EXCLUDED.account_status;

INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000006', 'Barletta', 1) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000006', 'Andria', 2) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000006', 'Trani', 3) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;

INSERT INTO professionals (
  id, legacy_id, category_id, category_slug, name, category_label,
  image_url, hero_image_url, avatar_color, bio, why_choose,
  rating, review_count, jobs_completed, price_per_hour, distance_km,
  available_today, verified, badge_document, badge_phone, badge_professional,
  base_city, service_areas, urgent_badge, is_new_featured, account_status
) VALUES (
  'b2000001-0001-4000-8000-000000000007', '900007', 'c1000001-0001-4000-8000-000000000001', 'pulizie', 'Sofia Marino', 'Pulizie',
  'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face', 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&h=600&fit=crop', '#EC4899',
  'Professionista verificato su Fidati, disponibile per interventi rapidi e lavori programmati.', '["Recensioni verificate","Prezzi trasparenti","Assicurazione RC professionale"]'::jsonb,
  4.8, 73, 175, 22, 0.5,
  true, true, true, true, true,
  'Trani', ARRAY['Trani', 'Barletta', 'Bisceglie']::TEXT[],
  NULL, true, 'verified'
) ON CONFLICT (id) DO UPDATE SET
  legacy_id = COALESCE(professionals.legacy_id, EXCLUDED.legacy_id),
  category_id = EXCLUDED.category_id,
  category_slug = EXCLUDED.category_slug,
  name = EXCLUDED.name,
  category_label = EXCLUDED.category_label,
  image_url = EXCLUDED.image_url,
  hero_image_url = EXCLUDED.hero_image_url,
  avatar_color = EXCLUDED.avatar_color,
  bio = EXCLUDED.bio,
  why_choose = EXCLUDED.why_choose,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  jobs_completed = EXCLUDED.jobs_completed,
  price_per_hour = EXCLUDED.price_per_hour,
  distance_km = EXCLUDED.distance_km,
  available_today = EXCLUDED.available_today,
  verified = EXCLUDED.verified,
  badge_document = EXCLUDED.badge_document,
  badge_phone = EXCLUDED.badge_phone,
  badge_professional = EXCLUDED.badge_professional,
  base_city = EXCLUDED.base_city,
  service_areas = EXCLUDED.service_areas,
  urgent_badge = EXCLUDED.urgent_badge,
  is_new_featured = EXCLUDED.is_new_featured,
  account_status = EXCLUDED.account_status;

INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000007', 'Trani', 1) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000007', 'Barletta', 2) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000007', 'Bisceglie', 3) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;

INSERT INTO professionals (
  id, legacy_id, category_id, category_slug, name, category_label,
  image_url, hero_image_url, avatar_color, bio, why_choose,
  rating, review_count, jobs_completed, price_per_hour, distance_km,
  available_today, verified, badge_document, badge_phone, badge_professional,
  base_city, service_areas, urgent_badge, is_new_featured, account_status
) VALUES (
  'b2000001-0001-4000-8000-000000000008', '900008', 'c1000001-0001-4000-8000-000000000004', 'giardinieri', 'Paolo Russo', 'Giardiniere',
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face', 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=600&fit=crop', '#10B981',
  'Professionista verificato su Fidati, disponibile per interventi rapidi e lavori programmati.', '["Recensioni verificate","Prezzi trasparenti","Assicurazione RC professionale"]'::jsonb,
  4.7, 52, 125, 30, 3.4,
  false, true, true, true, true,
  'Barletta', ARRAY['Barletta', 'Andria']::TEXT[],
  NULL, false, 'verified'
) ON CONFLICT (id) DO UPDATE SET
  legacy_id = COALESCE(professionals.legacy_id, EXCLUDED.legacy_id),
  category_id = EXCLUDED.category_id,
  category_slug = EXCLUDED.category_slug,
  name = EXCLUDED.name,
  category_label = EXCLUDED.category_label,
  image_url = EXCLUDED.image_url,
  hero_image_url = EXCLUDED.hero_image_url,
  avatar_color = EXCLUDED.avatar_color,
  bio = EXCLUDED.bio,
  why_choose = EXCLUDED.why_choose,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  jobs_completed = EXCLUDED.jobs_completed,
  price_per_hour = EXCLUDED.price_per_hour,
  distance_km = EXCLUDED.distance_km,
  available_today = EXCLUDED.available_today,
  verified = EXCLUDED.verified,
  badge_document = EXCLUDED.badge_document,
  badge_phone = EXCLUDED.badge_phone,
  badge_professional = EXCLUDED.badge_professional,
  base_city = EXCLUDED.base_city,
  service_areas = EXCLUDED.service_areas,
  urgent_badge = EXCLUDED.urgent_badge,
  is_new_featured = EXCLUDED.is_new_featured,
  account_status = EXCLUDED.account_status;

INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000008', 'Barletta', 1) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000008', 'Andria', 2) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;

INSERT INTO professionals (
  id, legacy_id, category_id, category_slug, name, category_label,
  image_url, hero_image_url, avatar_color, bio, why_choose,
  rating, review_count, jobs_completed, price_per_hour, distance_km,
  available_today, verified, badge_document, badge_phone, badge_professional,
  base_city, service_areas, urgent_badge, is_new_featured, account_status
) VALUES (
  'b2000001-0001-4000-8000-000000000009', '900009', 'c1000001-0001-4000-8000-000000000004', 'giardinieri', 'Matteo Verde', 'Giardiniere',
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face', 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=600&fit=crop', '#059669',
  'Professionista verificato su Fidati, disponibile per interventi rapidi e lavori programmati.', '["Recensioni verificate","Prezzi trasparenti","Assicurazione RC professionale"]'::jsonb,
  4.8, 61, 146, 28, 2.8,
  true, true, true, true, true,
  'Andria', ARRAY['Andria', 'Barletta', 'Trani']::TEXT[],
  NULL, false, 'verified'
) ON CONFLICT (id) DO UPDATE SET
  legacy_id = COALESCE(professionals.legacy_id, EXCLUDED.legacy_id),
  category_id = EXCLUDED.category_id,
  category_slug = EXCLUDED.category_slug,
  name = EXCLUDED.name,
  category_label = EXCLUDED.category_label,
  image_url = EXCLUDED.image_url,
  hero_image_url = EXCLUDED.hero_image_url,
  avatar_color = EXCLUDED.avatar_color,
  bio = EXCLUDED.bio,
  why_choose = EXCLUDED.why_choose,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  jobs_completed = EXCLUDED.jobs_completed,
  price_per_hour = EXCLUDED.price_per_hour,
  distance_km = EXCLUDED.distance_km,
  available_today = EXCLUDED.available_today,
  verified = EXCLUDED.verified,
  badge_document = EXCLUDED.badge_document,
  badge_phone = EXCLUDED.badge_phone,
  badge_professional = EXCLUDED.badge_professional,
  base_city = EXCLUDED.base_city,
  service_areas = EXCLUDED.service_areas,
  urgent_badge = EXCLUDED.urgent_badge,
  is_new_featured = EXCLUDED.is_new_featured,
  account_status = EXCLUDED.account_status;

INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000009', 'Andria', 1) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000009', 'Barletta', 2) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000009', 'Trani', 3) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;

INSERT INTO professionals (
  id, legacy_id, category_id, category_slug, name, category_label,
  image_url, hero_image_url, avatar_color, bio, why_choose,
  rating, review_count, jobs_completed, price_per_hour, distance_km,
  available_today, verified, badge_document, badge_phone, badge_professional,
  base_city, service_areas, urgent_badge, is_new_featured, account_status
) VALUES (
  'b2000001-0001-4000-8000-000000000010', '900010', 'c1000001-0001-4000-8000-000000000005', 'fabbri', 'Giuseppe Ferro', 'Fabbro',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face', 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop', '#78716C',
  'Professionista verificato su Fidati, disponibile per interventi rapidi e lavori programmati.', '["Recensioni verificate","Prezzi trasparenti","Assicurazione RC professionale"]'::jsonb,
  4.9, 58, 139, 50, 1,
  true, true, true, true, true,
  'Barletta', ARRAY['Barletta', 'Andria', 'Trani']::TEXT[],
  'Entro 2 ore', false, 'verified'
) ON CONFLICT (id) DO UPDATE SET
  legacy_id = COALESCE(professionals.legacy_id, EXCLUDED.legacy_id),
  category_id = EXCLUDED.category_id,
  category_slug = EXCLUDED.category_slug,
  name = EXCLUDED.name,
  category_label = EXCLUDED.category_label,
  image_url = EXCLUDED.image_url,
  hero_image_url = EXCLUDED.hero_image_url,
  avatar_color = EXCLUDED.avatar_color,
  bio = EXCLUDED.bio,
  why_choose = EXCLUDED.why_choose,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  jobs_completed = EXCLUDED.jobs_completed,
  price_per_hour = EXCLUDED.price_per_hour,
  distance_km = EXCLUDED.distance_km,
  available_today = EXCLUDED.available_today,
  verified = EXCLUDED.verified,
  badge_document = EXCLUDED.badge_document,
  badge_phone = EXCLUDED.badge_phone,
  badge_professional = EXCLUDED.badge_professional,
  base_city = EXCLUDED.base_city,
  service_areas = EXCLUDED.service_areas,
  urgent_badge = EXCLUDED.urgent_badge,
  is_new_featured = EXCLUDED.is_new_featured,
  account_status = EXCLUDED.account_status;

INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000010', 'Barletta', 1) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000010', 'Andria', 2) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000010', 'Trani', 3) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;

INSERT INTO professionals (
  id, legacy_id, category_id, category_slug, name, category_label,
  image_url, hero_image_url, avatar_color, bio, why_choose,
  rating, review_count, jobs_completed, price_per_hour, distance_km,
  available_today, verified, badge_document, badge_phone, badge_professional,
  base_city, service_areas, urgent_badge, is_new_featured, account_status
) VALUES (
  'b2000001-0001-4000-8000-000000000011', '900011', 'c1000001-0001-4000-8000-000000000005', 'fabbri', 'Antonio Serrature', 'Fabbro',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face', 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&h=600&fit=crop', '#57534E',
  'Professionista verificato su Fidati, disponibile per interventi rapidi e lavori programmati.', '["Recensioni verificate","Prezzi trasparenti","Assicurazione RC professionale"]'::jsonb,
  4.7, 44, 106, 48, 2.2,
  true, true, true, true, true,
  'Trani', ARRAY['Trani', 'Barletta', 'Bisceglie']::TEXT[],
  NULL, false, 'verified'
) ON CONFLICT (id) DO UPDATE SET
  legacy_id = COALESCE(professionals.legacy_id, EXCLUDED.legacy_id),
  category_id = EXCLUDED.category_id,
  category_slug = EXCLUDED.category_slug,
  name = EXCLUDED.name,
  category_label = EXCLUDED.category_label,
  image_url = EXCLUDED.image_url,
  hero_image_url = EXCLUDED.hero_image_url,
  avatar_color = EXCLUDED.avatar_color,
  bio = EXCLUDED.bio,
  why_choose = EXCLUDED.why_choose,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  jobs_completed = EXCLUDED.jobs_completed,
  price_per_hour = EXCLUDED.price_per_hour,
  distance_km = EXCLUDED.distance_km,
  available_today = EXCLUDED.available_today,
  verified = EXCLUDED.verified,
  badge_document = EXCLUDED.badge_document,
  badge_phone = EXCLUDED.badge_phone,
  badge_professional = EXCLUDED.badge_professional,
  base_city = EXCLUDED.base_city,
  service_areas = EXCLUDED.service_areas,
  urgent_badge = EXCLUDED.urgent_badge,
  is_new_featured = EXCLUDED.is_new_featured,
  account_status = EXCLUDED.account_status;

INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000011', 'Trani', 1) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000011', 'Barletta', 2) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000011', 'Bisceglie', 3) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;

INSERT INTO professionals (
  id, legacy_id, category_id, category_slug, name, category_label,
  image_url, hero_image_url, avatar_color, bio, why_choose,
  rating, review_count, jobs_completed, price_per_hour, distance_km,
  available_today, verified, badge_document, badge_phone, badge_professional,
  base_city, service_areas, urgent_badge, is_new_featured, account_status
) VALUES (
  'b2000001-0001-4000-8000-000000000012', '900012', 'c1000001-0001-4000-8000-000000000011', 'montaggio-mobili', 'Luca Conti', 'Montaggio mobili',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face', 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop', '#6366F1',
  'Professionista verificato su Fidati, disponibile per interventi rapidi e lavori programmati.', '["Recensioni verificate","Prezzi trasparenti","Assicurazione RC professionale"]'::jsonb,
  4.6, 98, 235, 35, 1.8,
  true, true, true, true, true,
  'Barletta', ARRAY['Barletta', 'Andria']::TEXT[],
  'Entro 2 ore', false, 'verified'
) ON CONFLICT (id) DO UPDATE SET
  legacy_id = COALESCE(professionals.legacy_id, EXCLUDED.legacy_id),
  category_id = EXCLUDED.category_id,
  category_slug = EXCLUDED.category_slug,
  name = EXCLUDED.name,
  category_label = EXCLUDED.category_label,
  image_url = EXCLUDED.image_url,
  hero_image_url = EXCLUDED.hero_image_url,
  avatar_color = EXCLUDED.avatar_color,
  bio = EXCLUDED.bio,
  why_choose = EXCLUDED.why_choose,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  jobs_completed = EXCLUDED.jobs_completed,
  price_per_hour = EXCLUDED.price_per_hour,
  distance_km = EXCLUDED.distance_km,
  available_today = EXCLUDED.available_today,
  verified = EXCLUDED.verified,
  badge_document = EXCLUDED.badge_document,
  badge_phone = EXCLUDED.badge_phone,
  badge_professional = EXCLUDED.badge_professional,
  base_city = EXCLUDED.base_city,
  service_areas = EXCLUDED.service_areas,
  urgent_badge = EXCLUDED.urgent_badge,
  is_new_featured = EXCLUDED.is_new_featured,
  account_status = EXCLUDED.account_status;

INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000012', 'Barletta', 1) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000012', 'Andria', 2) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;

INSERT INTO professionals (
  id, legacy_id, category_id, category_slug, name, category_label,
  image_url, hero_image_url, avatar_color, bio, why_choose,
  rating, review_count, jobs_completed, price_per_hour, distance_km,
  available_today, verified, badge_document, badge_phone, badge_professional,
  base_city, service_areas, urgent_badge, is_new_featured, account_status
) VALUES (
  'b2000001-0001-4000-8000-000000000013', '900013', 'c1000001-0001-4000-8000-000000000008', 'caldaie', 'Nicola Caldaie', 'Caldaie',
  'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&h=200&fit=crop&crop=face', 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=800&h=600&fit=crop', '#EF4444',
  'Professionista verificato su Fidati, disponibile per interventi rapidi e lavori programmati.', '["Recensioni verificate","Prezzi trasparenti","Assicurazione RC professionale"]'::jsonb,
  4.8, 47, 113, 70, 1.6,
  true, true, true, true, true,
  'Barletta', ARRAY['Barletta', 'Andria', 'Trani']::TEXT[],
  NULL, false, 'verified'
) ON CONFLICT (id) DO UPDATE SET
  legacy_id = COALESCE(professionals.legacy_id, EXCLUDED.legacy_id),
  category_id = EXCLUDED.category_id,
  category_slug = EXCLUDED.category_slug,
  name = EXCLUDED.name,
  category_label = EXCLUDED.category_label,
  image_url = EXCLUDED.image_url,
  hero_image_url = EXCLUDED.hero_image_url,
  avatar_color = EXCLUDED.avatar_color,
  bio = EXCLUDED.bio,
  why_choose = EXCLUDED.why_choose,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  jobs_completed = EXCLUDED.jobs_completed,
  price_per_hour = EXCLUDED.price_per_hour,
  distance_km = EXCLUDED.distance_km,
  available_today = EXCLUDED.available_today,
  verified = EXCLUDED.verified,
  badge_document = EXCLUDED.badge_document,
  badge_phone = EXCLUDED.badge_phone,
  badge_professional = EXCLUDED.badge_professional,
  base_city = EXCLUDED.base_city,
  service_areas = EXCLUDED.service_areas,
  urgent_badge = EXCLUDED.urgent_badge,
  is_new_featured = EXCLUDED.is_new_featured,
  account_status = EXCLUDED.account_status;

INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000013', 'Barletta', 1) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000013', 'Andria', 2) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000013', 'Trani', 3) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;

INSERT INTO professionals (
  id, legacy_id, category_id, category_slug, name, category_label,
  image_url, hero_image_url, avatar_color, bio, why_choose,
  rating, review_count, jobs_completed, price_per_hour, distance_km,
  available_today, verified, badge_document, badge_phone, badge_professional,
  base_city, service_areas, urgent_badge, is_new_featured, account_status
) VALUES (
  'b2000001-0001-4000-8000-000000000014', '900014', 'c1000001-0001-4000-8000-000000000013', 'condizionatori', 'Alberto Condizion', 'Condizionatori',
  'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face', 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=800&h=600&fit=crop', '#06B6D4',
  'Professionista verificato su Fidati, disponibile per interventi rapidi e lavori programmati.', '["Recensioni verificate","Prezzi trasparenti","Assicurazione RC professionale"]'::jsonb,
  4.7, 41, 98, 80, 2.4,
  true, true, true, true, true,
  'Andria', ARRAY['Andria', 'Barletta', 'Trani']::TEXT[],
  NULL, false, 'verified'
) ON CONFLICT (id) DO UPDATE SET
  legacy_id = COALESCE(professionals.legacy_id, EXCLUDED.legacy_id),
  category_id = EXCLUDED.category_id,
  category_slug = EXCLUDED.category_slug,
  name = EXCLUDED.name,
  category_label = EXCLUDED.category_label,
  image_url = EXCLUDED.image_url,
  hero_image_url = EXCLUDED.hero_image_url,
  avatar_color = EXCLUDED.avatar_color,
  bio = EXCLUDED.bio,
  why_choose = EXCLUDED.why_choose,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  jobs_completed = EXCLUDED.jobs_completed,
  price_per_hour = EXCLUDED.price_per_hour,
  distance_km = EXCLUDED.distance_km,
  available_today = EXCLUDED.available_today,
  verified = EXCLUDED.verified,
  badge_document = EXCLUDED.badge_document,
  badge_phone = EXCLUDED.badge_phone,
  badge_professional = EXCLUDED.badge_professional,
  base_city = EXCLUDED.base_city,
  service_areas = EXCLUDED.service_areas,
  urgent_badge = EXCLUDED.urgent_badge,
  is_new_featured = EXCLUDED.is_new_featured,
  account_status = EXCLUDED.account_status;

INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000014', 'Andria', 1) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000014', 'Barletta', 2) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000014', 'Trani', 3) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;

INSERT INTO professionals (
  id, legacy_id, category_id, category_slug, name, category_label,
  image_url, hero_image_url, avatar_color, bio, why_choose,
  rating, review_count, jobs_completed, price_per_hour, distance_km,
  available_today, verified, badge_document, badge_phone, badge_professional,
  base_city, service_areas, urgent_badge, is_new_featured, account_status
) VALUES (
  'b2000001-0001-4000-8000-000000000015', '900015', 'c1000001-0001-4000-8000-000000000007', 'serramentisti', 'Michele Infissi', 'Infissi',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face', 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&h=600&fit=crop', '#0EA5E9',
  'Professionista verificato su Fidati, disponibile per interventi rapidi e lavori programmati.', '["Recensioni verificate","Prezzi trasparenti","Assicurazione RC professionale"]'::jsonb,
  4.6, 38, 91, 55, 1.9,
  false, true, true, true, true,
  'Barletta', ARRAY['Barletta', 'Trani']::TEXT[],
  NULL, false, 'verified'
) ON CONFLICT (id) DO UPDATE SET
  legacy_id = COALESCE(professionals.legacy_id, EXCLUDED.legacy_id),
  category_id = EXCLUDED.category_id,
  category_slug = EXCLUDED.category_slug,
  name = EXCLUDED.name,
  category_label = EXCLUDED.category_label,
  image_url = EXCLUDED.image_url,
  hero_image_url = EXCLUDED.hero_image_url,
  avatar_color = EXCLUDED.avatar_color,
  bio = EXCLUDED.bio,
  why_choose = EXCLUDED.why_choose,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  jobs_completed = EXCLUDED.jobs_completed,
  price_per_hour = EXCLUDED.price_per_hour,
  distance_km = EXCLUDED.distance_km,
  available_today = EXCLUDED.available_today,
  verified = EXCLUDED.verified,
  badge_document = EXCLUDED.badge_document,
  badge_phone = EXCLUDED.badge_phone,
  badge_professional = EXCLUDED.badge_professional,
  base_city = EXCLUDED.base_city,
  service_areas = EXCLUDED.service_areas,
  urgent_badge = EXCLUDED.urgent_badge,
  is_new_featured = EXCLUDED.is_new_featured,
  account_status = EXCLUDED.account_status;

INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000015', 'Barletta', 1) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000015', 'Trani', 2) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;

INSERT INTO professionals (
  id, legacy_id, category_id, category_slug, name, category_label,
  image_url, hero_image_url, avatar_color, bio, why_choose,
  rating, review_count, jobs_completed, price_per_hour, distance_km,
  available_today, verified, badge_document, badge_phone, badge_professional,
  base_city, service_areas, urgent_badge, is_new_featured, account_status
) VALUES (
  'b2000001-0001-4000-8000-000000000016', '900016', 'c1000001-0001-4000-8000-000000000006', 'imbianchini', 'Simone Riva', 'Imbianchino',
  'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&h=200&fit=crop&crop=face', 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop', '#475569',
  'Professionista verificato su Fidati, disponibile per interventi rapidi e lavori programmati.', '["Recensioni verificate","Prezzi trasparenti","Assicurazione RC professionale"]'::jsonb,
  4.5, 78, 187, 30, 2.6,
  true, true, true, true, true,
  'Trani', ARRAY['Trani', 'Barletta', 'Andria']::TEXT[],
  NULL, false, 'verified'
) ON CONFLICT (id) DO UPDATE SET
  legacy_id = COALESCE(professionals.legacy_id, EXCLUDED.legacy_id),
  category_id = EXCLUDED.category_id,
  category_slug = EXCLUDED.category_slug,
  name = EXCLUDED.name,
  category_label = EXCLUDED.category_label,
  image_url = EXCLUDED.image_url,
  hero_image_url = EXCLUDED.hero_image_url,
  avatar_color = EXCLUDED.avatar_color,
  bio = EXCLUDED.bio,
  why_choose = EXCLUDED.why_choose,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  jobs_completed = EXCLUDED.jobs_completed,
  price_per_hour = EXCLUDED.price_per_hour,
  distance_km = EXCLUDED.distance_km,
  available_today = EXCLUDED.available_today,
  verified = EXCLUDED.verified,
  badge_document = EXCLUDED.badge_document,
  badge_phone = EXCLUDED.badge_phone,
  badge_professional = EXCLUDED.badge_professional,
  base_city = EXCLUDED.base_city,
  service_areas = EXCLUDED.service_areas,
  urgent_badge = EXCLUDED.urgent_badge,
  is_new_featured = EXCLUDED.is_new_featured,
  account_status = EXCLUDED.account_status;

INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000016', 'Trani', 1) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000016', 'Barletta', 2) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000016', 'Andria', 3) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;

INSERT INTO professionals (
  id, legacy_id, category_id, category_slug, name, category_label,
  image_url, hero_image_url, avatar_color, bio, why_choose,
  rating, review_count, jobs_completed, price_per_hour, distance_km,
  available_today, verified, badge_document, badge_phone, badge_professional,
  base_city, service_areas, urgent_badge, is_new_featured, account_status
) VALUES (
  'b2000001-0001-4000-8000-000000000017', '900017', 'c1000001-0001-4000-8000-000000000010', 'antennisti', 'Davide Antenne', 'Antennista',
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face', 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=600&fit=crop', '#8B5CF6',
  'Professionista verificato su Fidati, disponibile per interventi rapidi e lavori programmati.', '["Recensioni verificate","Prezzi trasparenti","Assicurazione RC professionale"]'::jsonb,
  4.6, 33, 79, 38, 1.3,
  true, true, true, true, true,
  'Barletta', ARRAY['Barletta', 'Andria', 'Bisceglie']::TEXT[],
  NULL, false, 'verified'
) ON CONFLICT (id) DO UPDATE SET
  legacy_id = COALESCE(professionals.legacy_id, EXCLUDED.legacy_id),
  category_id = EXCLUDED.category_id,
  category_slug = EXCLUDED.category_slug,
  name = EXCLUDED.name,
  category_label = EXCLUDED.category_label,
  image_url = EXCLUDED.image_url,
  hero_image_url = EXCLUDED.hero_image_url,
  avatar_color = EXCLUDED.avatar_color,
  bio = EXCLUDED.bio,
  why_choose = EXCLUDED.why_choose,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  jobs_completed = EXCLUDED.jobs_completed,
  price_per_hour = EXCLUDED.price_per_hour,
  distance_km = EXCLUDED.distance_km,
  available_today = EXCLUDED.available_today,
  verified = EXCLUDED.verified,
  badge_document = EXCLUDED.badge_document,
  badge_phone = EXCLUDED.badge_phone,
  badge_professional = EXCLUDED.badge_professional,
  base_city = EXCLUDED.base_city,
  service_areas = EXCLUDED.service_areas,
  urgent_badge = EXCLUDED.urgent_badge,
  is_new_featured = EXCLUDED.is_new_featured,
  account_status = EXCLUDED.account_status;

INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000017', 'Barletta', 1) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000017', 'Andria', 2) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000017', 'Bisceglie', 3) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;

INSERT INTO professionals (
  id, legacy_id, category_id, category_slug, name, category_label,
  image_url, hero_image_url, avatar_color, bio, why_choose,
  rating, review_count, jobs_completed, price_per_hour, distance_km,
  available_today, verified, badge_document, badge_phone, badge_professional,
  base_city, service_areas, urgent_badge, is_new_featured, account_status
) VALUES (
  'b2000001-0001-4000-8000-000000000018', '900018', 'c1000001-0001-4000-8000-000000000009', 'traslochi-sgomberi', 'Pietro Traslochi', 'Traslochi e sgomberi',
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face', 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=600&fit=crop', '#A78BFA',
  'Professionista verificato su Fidati, disponibile per interventi rapidi e lavori programmati.', '["Recensioni verificate","Prezzi trasparenti","Assicurazione RC professionale"]'::jsonb,
  4.5, 39, 94, 45, 2.5,
  false, true, true, true, true,
  'Barletta', ARRAY['Barletta', 'Andria', 'Trani', 'Bisceglie']::TEXT[],
  NULL, false, 'verified'
) ON CONFLICT (id) DO UPDATE SET
  legacy_id = COALESCE(professionals.legacy_id, EXCLUDED.legacy_id),
  category_id = EXCLUDED.category_id,
  category_slug = EXCLUDED.category_slug,
  name = EXCLUDED.name,
  category_label = EXCLUDED.category_label,
  image_url = EXCLUDED.image_url,
  hero_image_url = EXCLUDED.hero_image_url,
  avatar_color = EXCLUDED.avatar_color,
  bio = EXCLUDED.bio,
  why_choose = EXCLUDED.why_choose,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  jobs_completed = EXCLUDED.jobs_completed,
  price_per_hour = EXCLUDED.price_per_hour,
  distance_km = EXCLUDED.distance_km,
  available_today = EXCLUDED.available_today,
  verified = EXCLUDED.verified,
  badge_document = EXCLUDED.badge_document,
  badge_phone = EXCLUDED.badge_phone,
  badge_professional = EXCLUDED.badge_professional,
  base_city = EXCLUDED.base_city,
  service_areas = EXCLUDED.service_areas,
  urgent_badge = EXCLUDED.urgent_badge,
  is_new_featured = EXCLUDED.is_new_featured,
  account_status = EXCLUDED.account_status;

INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000018', 'Barletta', 1) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000018', 'Andria', 2) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000018', 'Trani', 3) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000018', 'Bisceglie', 4) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;

INSERT INTO professionals (
  id, legacy_id, category_id, category_slug, name, category_label,
  image_url, hero_image_url, avatar_color, bio, why_choose,
  rating, review_count, jobs_completed, price_per_hour, distance_km,
  available_today, verified, badge_document, badge_phone, badge_professional,
  base_city, service_areas, urgent_badge, is_new_featured, account_status
) VALUES (
  'b2000001-0001-4000-8000-000000000019', '900019', 'c1000001-0001-4000-8000-000000000012', 'tende-da-sole', 'Luigi Tende', 'Tende da sole',
  'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&h=200&fit=crop&crop=face', 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=800&h=600&fit=crop', '#FB7185',
  'Professionista verificato su Fidati, disponibile per interventi rapidi e lavori programmati.', '["Recensioni verificate","Prezzi trasparenti","Assicurazione RC professionale"]'::jsonb,
  4.6, 36, 86, 42, 3.3,
  true, true, true, true, true,
  'Trani', ARRAY['Trani', 'Barletta']::TEXT[],
  NULL, false, 'verified'
) ON CONFLICT (id) DO UPDATE SET
  legacy_id = COALESCE(professionals.legacy_id, EXCLUDED.legacy_id),
  category_id = EXCLUDED.category_id,
  category_slug = EXCLUDED.category_slug,
  name = EXCLUDED.name,
  category_label = EXCLUDED.category_label,
  image_url = EXCLUDED.image_url,
  hero_image_url = EXCLUDED.hero_image_url,
  avatar_color = EXCLUDED.avatar_color,
  bio = EXCLUDED.bio,
  why_choose = EXCLUDED.why_choose,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  jobs_completed = EXCLUDED.jobs_completed,
  price_per_hour = EXCLUDED.price_per_hour,
  distance_km = EXCLUDED.distance_km,
  available_today = EXCLUDED.available_today,
  verified = EXCLUDED.verified,
  badge_document = EXCLUDED.badge_document,
  badge_phone = EXCLUDED.badge_phone,
  badge_professional = EXCLUDED.badge_professional,
  base_city = EXCLUDED.base_city,
  service_areas = EXCLUDED.service_areas,
  urgent_badge = EXCLUDED.urgent_badge,
  is_new_featured = EXCLUDED.is_new_featured,
  account_status = EXCLUDED.account_status;

INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000019', 'Trani', 1) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;
INSERT INTO professional_zones (professional_id, zone_name, sort_order) VALUES ('b2000001-0001-4000-8000-000000000019', 'Barletta', 2) ON CONFLICT (professional_id, zone_name) DO UPDATE SET sort_order = EXCLUDED.sort_order;

-- Garantisce Barletta in service_areas per i seed (idempotente)
UPDATE professionals SET
  service_areas = CASE
    WHEN service_areas IS NULL OR array_length(service_areas, 1) IS NULL THEN ARRAY['Barletta']::TEXT[]
    WHEN NOT ('Barletta' = ANY(service_areas)) THEN array_prepend('Barletta', service_areas)
    ELSE service_areas
  END
WHERE id::text LIKE 'b2000001-0001-4000-8000-%';
